# Generated by Django 5.2.8 on 2025-11-22 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actualizado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='anio',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
